### ISSUE TITLE
type error when converting gl texture handle to c_void_p

### ISSUE THREAD

**Issue by jzitelli** [cmbruns/pyopenvr#20]
I experience the following error when running the hello_* examples using 64-bit Python 3.5 (Anaconda distribution):
```
$ python hello_sdl2.py
SdlApp exiting
Traceback (most recent call last):
  File "hello_sdl2.py", line 20, in <module>
    app.run_loop()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\glframework\sdl_app.py", line 122, in run_loop
    self.render_scene()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\glframework\sdl_app.py", line 79, in render_scene
    self.init_gl() # should be a no-op after the first frame is rendered
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\glframework\sdl_app.py", line 74, in init_gl
    self.renderer.init_gl()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\gl_renderer.py", line 153, in init_gl
    self.left_fb.init_gl()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\gl_renderer.py", line 98, in init_gl
    self.texture.handle = self.resolve_texture_id
TypeError: cannot be converted to pointer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_sdl2.py", line 20, in <module>
    app.run_loop()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\glframework\sdl_app.py", line 47, in __exit__
    self.dispose_gl()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\glframework\sdl_app.py", line 90, in dispose_gl
    self.renderer.dispose_gl()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\gl_renderer.py", line 217, in dispose_gl
    actor.dispose_gl()
  File "C:\Users\zemed\Anaconda3\lib\site-packages\openvr\color_cube_actor.py", line 119, in dispose_gl
    glDeleteVertexArrays(1, (self.vao,))
AttributeError: 'ColorCubeActor' object has no attribute 'vao'
```

I changed the `handle` field in the `Texture_t` ctypes structure from `c_void_p` to `c_uint32` and the problem was fixed... my understanding is that the handles/ids generated by OpenGL will always be 32 bit unsigned int, regardless of the client (32 vs. 64 bit) platform, so `c_uint32` is the appropriate type if you are running 64-bit libs.  Does that sound right?

**Comment by cmbruns-hhmi** [comment]
Thank you for reporting this.

It appears that the Texture_t.handle really is a void*, not a uint32
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_capi.h#L1022
and
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L123
So I would expect the alignment of the Texture_t struct to become wrong if we change Texture_t.handle to a uint32.
Rather, I suspect we need a different way to coerce a python integer to a 64-bit pointer, which seems to be what openvr expects us to do.

And of course we need to avoid that other exception, probably by initializing vao to None or zero at the start.

I have actually never tested 64-bit openvr. Aside from this problem, is it working for you? If so, that's great news.

**Comment by jzitelli** [comment]
64-bit openvr is working for me!  But you're right, looking at the OpenGL spec I see that actually the GLuint handle type is only a minimum of 32 bits, and I assume that openvr has made the right type choices...

Somewhat related: I've now been modifying the arguments to some of the gl calls (such as the delete vao that throws the other exception above) to pass in types that expose native ctypes pointers (to avoid any overhead of copy conversion from Python tuples or other types - you can set PyOpenGL to throw exceptions when this happens).  I think this is a good practice to maximize performance.  PyOpenGL has a "raw" API which does not perform any implicit conversions, and maybe it's best to use that while also explicitly performing any type conversions that might be necessary - I'll try that and see how it goes.
