### ISSUE TITLE
Unable to read VR Path Registry from /home/marco/.config/openvr/openvrpaths.vrpath

### ISSUE THREAD

**Issue by chopin1998** [cmbruns/pyopenvr#53]
after install, i can import openvr correctly,

but hello.py show:

> Unable to read VR Path Registry from /home/marco/.config/openvr/openvrpaths.vrpath

and

> Traceback (most recent call last):
>   File "hello.py", line 15, in <module>
>     vr_system = openvr.init(openvr.VRApplication_Scene)
>   File "/usr/local/lib/python2.7/dist-packages/openvr-1.0.1701-py2.7.egg/openvr/__init__.py", line 6039, in init
>     initInternal2(applicationType, pStartupInfo)
>   File "/usr/local/lib/python2.7/dist-packages/openvr-1.0.1701-py2.7.egg/openvr/__init__.py", line 6143, in initInternal2
>     _checkInitError(error.value)
>   File "/usr/local/lib/python2.7/dist-packages/openvr-1.0.1701-py2.7.egg/openvr/__init__.py", line 6025, in _checkInitError
>     raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
> openvr.OpenVRError: VRInitError_Init_PathRegistryNotFound (error number 110)
>

**Comment by ahmedbaza** [comment]
hey, did you find any way around it ?

**Comment by chopin1998** [comment]
> hey, did you find any way around it ?

i use this:
self.vr = openvr.init(openvr.VRApplication_Other)
