### ISSUE TITLE
PB : VR Path Registry node config is not an array 

### ISSUE THREAD

**Issue by PannetierJ** [cmbruns/pyopenvr#55]
Hello , 
I'm writing you about your library. I tried to install this on Ubuntu 18.04. 
When i tried to start , nevertheless I have an error message : 
python3.6 ./tracker_test.py
VR Path Registry node config is not an array
VR Path Registry node log is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array
Traceback (most recent call last):
File "./tracker_test.py", line 5, in
v = triad_openvr.triad_openvr()
File "/home/jpannnetier/Documents/DevelopmentPython/Triad Open VR/triad_openvr-master/triad_openvr.py", line 107, in init
self.vr = openvr.init(openvr.VRApplication_Other)
File "/usr/local/lib/python3.6/dist-packages/openvr/init.py", line 6039, in init
initInternal2(applicationType, pStartupInfo)
File "/usr/local/lib/python3.6/dist-packages/openvr/init.py", line 6143, in initInternal2
_checkInitError(error.value)
File "/usr/local/lib/python3.6/dist-packages/openvr/init.py", line 6025, in _checkInitError
raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
openvr.OpenVRError: b'VRInitError_Init_NoConfigPath' (error number 111)

**Comment by cmbruns** [comment]
@PannetierJ this might be related to the issue at 
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/89
Perhaps you could try the workaround there.
