### ISSUE TITLE
Installation error: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by eambutu** [cmbruns/pyopenvr#68]
Hi, trying to set this up on Windows 10 on Python 3.7.4. This is my stacktrace/process for installing openvr:

```
PS C:\Users\phill> pip install openvr
Collecting openvr
  Using cached https://files.pythonhosted.org/packages/80/40/0d5fa1efaf9e3b85bc95c799022d526108adf4bb29e2623aeb68ed778cb5/openvr-1.5.1701.tar.gz
Installing collected packages: openvr
  Running setup.py install for openvr ... done
Successfully installed openvr-1.5.1701
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\phill> python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:13:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import openvr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\phill\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\openvr\__init__.py", line 58, in <module>
    _openvr = cdll.LoadLibrary(_openvr_lib_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Any tips? Apologies if I'm just doing something really stupid.

**Comment by MrAlexEsisteGia** [comment]
I'm a noob at this but if i was you, i wouldn't use python from the microsoft store, just sayin'
