### ISSUE TITLE
openvr.error_code.CompositorError_InvalidTexture

### ISSUE THREAD

**Issue by Toni-SM** [cmbruns/pyopenvr#87]
Hi

I am getting the ```openvr.error_code.CompositorError_InvalidTexture``` with all samples.

For example:

```
Traceback (most recent call last):
  File "hello_glfw3.py", line 18, in <module>
    glfwApp.run_loop()
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/glframework/glfw_app.py", line 83, in run_loop
    self.render_scene()
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/glframework/glfw_app.py", line 60, in render_scene
    self.renderer.render_scene()
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/gl_renderer.py", line 198, in render_scene
    self.left_fb.submit(openvr.Eye_Left)
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/gl_renderer.py", line 112, in submit
    openvr.VRCompositor().submit(eye, self.texture)
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/__init__.py", line 4409, in submit
    openvr.error_code.CompositorError.check_error_value(error)
  File "/home/argus/.local/lib/python3.6/site-packages/openvr/error_code/__init__.py", line 23, in check_error_value
    raise error_class(error_value, message)
openvr.error_code.CompositorError_InvalidTexture
```

**Comment by cmbruns** [comment]
@Toni-SM Thank you for your report. The samples are still working for me. Perhaps there is something specific about your setup.

Are other vr applications working correctly?

Are other OpenGL based vr applications working correctly?

Are you able to successfully compile and run the C++ samples from https://github.com/ValveSoftware/openvr ?

Have the samples for this project ever worked on your setup? If so, can you think of what might have changed?

From the file names in the stack trace I would guess you are running some sort of linux or unix operating system. I don't have a linux vr setup so I cannot help debug that aspect. What exact OS version are you using?

What VR hardware are you using? I'm using an original HTC Vive. This project has had more testing with Windows/Vive than with other configurations.
